name: crisp_sdk
description: "Crisp SDK for user can use Crisp chat in their flutter app."
version: 1.1.0
homepage: "https://github.com/AmirJabbari/crisp_sdk"
publish_to: "pub.dev"

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  url_launcher: ^6.2.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

